---
title: "Применение средств и методов OSINT"
author: "Серняев А.О. БИСО-01-20 вариант - 26"
format:
    md:
        output-file: README.md
engine: knitr
---

## Цель работы

1)  Освоить базовые подходы процессов OSINT
2)  Освоить современные инструменты поиска и сбора информации
3)  Освоить инструменты совместной работы в ходе аналитической деятельности

## Ход работы

Собрать публичную информацию об компании создавшую операционную систему Astra Linux

## Шаг 1. Инфорация о компании

Гк «Астра» (ООО «РусБИТех-Астра) - один из лидеров российский IT-индустрии, ведущий производитель программного обеспечения, в том числе защищённых операционных систем и платформ виртуализации. Генеральный директор ГК «Астра» - Сивцев Илья Игоревич ГК «Астра» -- член ассоциации «Руссофт» и АРПП, обладатель множества дипломов, лауреат национальных и международных премий за уникальные решения в области создания и реализации защищенных информационных систем Сама компания расположена по адресу: Россия, Центральный ФО РФ,г. Москва, 117105, Варшавское шоссе, д. 26 Информация взята с сайта - https://astralinux.ru/about

## Шаг 2. Экосистема компании

По данным генерального директора компании - «Ильи Сивцева» в 2022 экосистема «Астра» насчитывала порядка 2 тыс. партнёрских отношений и решений. А если посмотреть на текущие сделки, которые уже в работе, то в следующем году можно ожидать показателя в 35% от всех продаж компании. Среди лидеров этого роста -- СУБД Tantor (разработка компании «Лаборатории Тантор» на основе открытой СУБД PostgreSQL), говорит гендиректор «Астры». При этом все лидеры роста в экосистеме относятся к серверному слою, отметил Илья Сивцев.

Информация взята с сайта - https://www.tadviser.ru/index.php/%D0%9A%D0%BE%D0%BC%D0%BF%D0%B0%D0%BD%D0%B8%D1%8F:%D0%A0%D1%83%D1%81%D0%91%D0%98%D0%A2%D0%B5%D1%85-%D0%90%D1%81%D1%82%D1%80%D0%B0\_(%D0%93%D0%9A_Astra_Linux)

## Шаг 3. Направленность компании

Основная направленность компании - разработка операционной системы на базе ядра Linux, которая внедряется в России в качестве альтернативы Microsoft Windows.

Продукты компании известные на 2023 год:

## Astra Linux Common Edition

Astra Linux Common Edition или же Astra Linux релиз «Орел» - единственная российская ОС, репозиторий которой размещен в открытом доступе международной некоммерческой организации The Linux Foundation.

Хранилище предоставляет доступ к 20 000 программным пакетам dl.astralinux.ru и mirror.yandex.ru/astra и официально признано деривативом Debian GNU/Linux, единственным развиваемым в Российской Федерации среди всего класса Debian Linux-систем в мире.

Astra Linux Common Edition используется в госучреждениях и корпорациях, чья требовательность к качеству IT-решений --- явный маркер высокого уровня их безопасности, надежности и удобства.

## Astra Linux Special Edition

Astra Linux Special Edition или же Astra Linux релиз «Смоленск» --- сертифицированная ОС со встроенными средствами защиты информации (СЗИ) для стабильных и безопасных ИТ-инфраструктур любого масштаба и бесперебойной работы с данными любой степени конфиденциальности

## Серверная базовая платформа

Astra Linux Server -- флагманский продукт ГК «Астра», консолидирующий в себе совокупность передаваемых прав (сценариев) использования и функциональную мощь лицензируемой для использования на серверах операционной системы специального назначения Astra Linux Special Edition

## Система виртуализации серверов

Программный комплекс «Средства виртуализации «БРЕСТ»» --- современный инструментарий для управления облачными виртуальными структурами любой сложности с применением средств защиты Astra Linux Special Edition.

## Система виртуализации рабочих мест

Termidesk реализует полнофункциональную инфраструктуру виртуальных рабочих мест для организации удаленной и безопасной работы сотрудников с любых устройств из любой точки мира.

## Средство резервного копирования

RuBackup - системное клиент-серверное приложение для автоматизированного резервного копирования и восстановления данных:виртуальных машин, физических серверов, облачных сервисов, баз данных, data-центров.

## Решение для централизованного управления и автоматизации

ALD Pro - программный комплекс на базе ОС Astra Linux предназначен для централизованного управления объектами организаций различного масштаба

## Астра консалтинг услуги

Astra Consulting предоставляет полномасштабный спектр консалтинговых услуг в рамках проектов перевода ИТ-инфраструктур организаций, обеспечивает полноценное сопровождение заказчиков в процессе миграции и внедрения отечественного ПО.

Информация взята с сайта - https://astralinux.ru/products/

## Шаг 4. Клиенты компании

Все продукты Astra Linux входят в реестр Минкомсвязи России. Их используют крупные предприятия, государственные корпорации, министерства и структуры, чья требовательность к качеству IT-решений маркер высокого уровня их безопасности, надёжности и удобства.

Информация взята с сайта - https://astralinux.ru/about

## Шаг 5. Веб-сайты компании и сотрудников

Главный веб-сайт компании - https://rusbitech.ru/ Веб-сайты продуктов - https://astralinux.ru/ https://wiki.astralinux.ru/ https://astralinux.axoft.ru/

## Шаг 6. Публичные сотрудники компании

## Гениральный директор - Сивцев Илья Игоревич

Сивцев Илья Игоревич родился 13 мая, 1987 года в Москве. Имеет высшеее экономическое образование, выпускник Московской школы управления «Сколково», специальность «Финансы и кредит». В 2017 году Илья Сивцев возглавляет ИТ-направление научно-производственного объединения «Русбитех» и вплотную занимается системным ПО. В том же году подразделение, разрабатывающее ОС Astra Linux, выделяется в самостоятельный бизнес-юнит -- ГК Astra Linux (основное юрлицо -- ООО «Русбитех-Астра»). Компания довольно быстро набирает обороты и за пару лет становится заметным игроком российского ИТ-рынка и ведущим отечественным разработчиком базовых программных продуктов -- операционных систем семейства Astra Linux и платформ виртуализации. На июнь 2020 года Astra Linux -- это комплексные решения, в основе которых лежит отечественная операционная система. Продукты компании востребованы у федеральных служб и ведомств, органов государственной власти субъектов РФ и муниципальных образований, госкорпораций и промышленных предприятий. За последние 2 года компания проделала большую работу и серьезно нарастила клиентскую базу. Среди проектов крупных внедрений можно выделить Минобороны России, Росгвардия, МВД России, дочерние структуры Росатома, Газпрома, Московское метро и др. На декабрь 2019 года -- операционный директор в АО «НПО РусБИТех».

Информация взята с сайта - https://www.tadviser.ru/index.php/%D0%9F%D0%B5%D1%80%D1%81%D0%BE%D0%BD%D0%B0:%D0%A1%D0%B8%D0%B2%D1%86%D0%B5%D0%B2\_%D0%98%D0%BB%D1%8C%D1%8F\_%D0%98%D0%B3%D0%BE%D1%80%D0%B5%D0%B2%D0%B8%D1%87

## Бугрецов Антон Юрьевич - коммерческий директор

С октября 2017 - коммерческий директор ООО «РусБИТех-Астра» (ГК Astra Linux).

Информация взята с сайта - https://www.tadviser.ru/index.php/%D0%9F%D0%B5%D1%80%D1%81%D0%BE%D0%BD%D0%B0:%D0%91%D1%83%D0%B3%D1%80%D0%B5%D1%86%D0%BE%D0%B2\_%D0%90%D0%BD%D1%82%D0%BE%D0%BD\_%D0%AE%D1%80%D1%8C%D0%B5%D0%B2%D0%B8%D1%87

## Соснин Юрий Владимирович - заместитель генирального директора

На январь 2020 года - заместитель генерального директора ООО «РусБИТех-Астра».

Информация взята с сайта - https://www.tadviser.ru/index.php/%D0%9F%D0%B5%D1%80%D1%81%D0%BE%D0%BD%D0%B0:%D0%A1%D0%BE%D1%81%D0%BD%D0%B8%D0%BD\_%D0%AE%D1%80%D0%B8%D0%B9\_%D0%92%D0%BB%D0%B0%D0%B4%D0%B8%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B8%D1%87 \## Шаг 7. Достижения компании

## Astra Linux стала первой ОС для работы с гостайной «особой важности»

В мае 2019 года ОС Astra Linux Special Edition (релиз «Смоленск», версия 1.6) была сертифицирована по требованиям ФСТЭК к операционным системам типа «А» 1-го класса защиты, став первой в истории России ОС, допущенной до работы с государственной тайной самой высокой степени секретности («особой важности») включительно.

В совокупности с ранее полученным сертификатом соответствия требованиям ФСБ РФ к средствам защиты информации, содержащей государственную тайну, сертификат ФСТЭК позволяет применять Astra Linux Special Edition (релиз «Смоленск») в информационных системах органов государственного и военного управления, включая высшие органы госвласти, для обработки любой информации ограниченного доступа.

## Версия для отечественных процессоров «Эльбрус» сертифицирована МО и ФСБ

Astra Linux Special Edition (релиз «Ленинград») для процессорной архитектуры «Эльбрус» успешно прошла инспекционный контроль Министерства обороны и ФСБ России. Сертификат, выданный МО, позволяет использовать операционную систему в автоматизированных системах в защищённом исполнении. Сертификат ФСБ подтверждает соответствие релиза «Ленинград» требованиям безопасности информации к средствам защиты информации, содержащей государственную тайну.

## Astra Linux стала лауреатом премии «Серебряный кинжал»

31 января 2018 года компания «РусБИТех-Астра» получила медаль и почётный диплом Профессиональной премии «Серебряный кинжал» в номинации «За реализованный проект в сфере обеспечения информационной безопасности». Награду компании-разработчику принёс всё тот же флагманский продукт --- Astra Linux Special Edition. При оценке заслуг «РусБИТех-Астра» жюри учитывало не только функционал и сертификаты безопасности ОС, но и реализованные на её основе проекты. В частности, в расчёт брались выстроенные на базе Astra Linux Special Edition автоматизированные системы в защищённом исполнении Правительства РФ, ФСО, Министерства обороны, МВД, Росгвардии, предприятий и объектов Росатома, правительств Челябинской области, Республики Северная Осетия - Алания.

## Отечественная ОС подтвердила свой экспортный потенциал

На базе российского программного обеспечения --- операционной системы ASTRALINUX Special Edition (ООО «РусБИТех-Астра») и SCADA-системы TRACE MODE (ООО «АдАстрА») --- был реализован проект внедрения системы автоматического пожаротушения Тяньваньской АЭС (Китай).

## Серебро конкурса «Проектный Олимп» за скорость внедрения

В рамках проекта миграции органов исполнительной власти Челябинской области на отечественную ОС было разработано уникальное техническое решение, позволяющее осуществлять перевод рабочих мест на Astra Linux Special Edition в полностью автоматизированном режиме, в короткие сроки, с минимумом накладных расходов. Проект был представлен на всероссийском конкурсе «Проектный Олимп» и завоевал серебро в номинации «Проекты в сфере импортозамещения и поддержки экспорта».

## Достигнута тотальная совместимость Astra Linux с программами 1С

В декабре 2018 года фирма «1С» подтвердила совместимость технологической платформы «1С:Предприятие 8» со всеми версиями операционной системы Astra Linux: Common Edition версий 1.11 и 2.12 и Special Edition версий 1.4, 1.5 и 1.6. Официальное подтверждение совместимости позволяет пользователям и администраторам Astra Linux быть уверенными в получении технической поддержки по вопросам, связанным с работой систем 1С. Это, пожалуй, самая важная новость для клиентов ГК «СофтЭксперт».

## Вывод

Были освоены базовые подходы процессов OSINT, современные инструменты поиска и сбора информации, а также инструменты современной работы в ходе аналитической деятельности.
